### ISSUE TITLE
Does Dynamsoft data matrix coder lib supports ARM64 architecture?

### ISSUE THREAD

**Issue by nullbyte91** [Dynamsoft/Dynamsoft-Barcode-Reader#2]
Hi Team,

I've downloaded the  dbr-rpi-7.6.tar.gz and export the LD lib path. I'm trying to compile the C++ Sample on aarch64 target.
And, I'm getting the below error,

```bash
gcc -o ReadMultiBarcodes ReadMultiBarcodes.o -lstdc++ -lDynamsoftBarcodeReader -L ../../../lib -Wl,-rpath=../../../lib -Wl,-rpath=./
/usr/bin/ld: skipping incompatible ../../../lib/libDynamsoftBarcodeReader.so when searching for -lDynamsoftBarcodeReader
/usr/bin/ld: cannot find -lDynamsoftBarcodeReader
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'ReadMultiBarcodes' failed
make: *** [ReadMultiBarcodes] Error 1
``` 

Is this a hardware compatibility issue?

Regards,
Jegathesan S

**Comment by yushulx** [comment]
@nullbyte91 it's built for ARM32. There's no aarch64 edition available online. You can get the aarch64 edition from dbr Python package `pip install dbr`. Please refer to the article: https://www.dynamsoft.com/codepool/jetson-nano-arm64-barcode-sdk.html

**Comment by nullbyte91** [comment]
@yushulx Thanks.
